detection:
  risk:
    amount:
      low: 0.0
      medium: 1000.0
      high: 5000.0
    high-risk-countries:
      - Mordor
      - Isengard
      - Angmar
    new-account-days: 90
  fraud:
    similarity-threshold: 0.9
    inflow:
      count: 3
      max-amount: 5000.0
    outflow:
      count: 1
      min-amount: 9000.0