spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/muletrapdb?currentSchema=muletrapschema,public
    username: muletrapadmin
    password: ${mule_db_password}
    driver-class-name: org.postgresql.Driver
    # HikariCP specific settings
    hikari:
      pool-name: MuleTrapPool
      minimum-idle: 5              # how many idle connections Hikari tries to maintain
      maximum-pool-size: 20        # the maximum number of actual connections
      connection-timeout: 30000    # max wait for a connection (ms) before timing out
      idle-timeout: 600000         # how long a connection can sit idle (ms) before being retired
      max-lifetime: 1800000        # maximum lifetime of a connection in the pool (ms)
      validation-timeout: 5000     # how long to wait for a connection validation (ms)
      leak-detection-threshold: 2000  # flag and log any connection not returned in this many ms
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: muletrapschema
        searchpath: muletrapschema,public