spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/muletrapdb
    username: muletrapadmin
    password: ${mule_db_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    banner-mode: "off"